version: "3"
services:

    web:
        build:
          context: ../
          dockerfile: ./docker/Dockerfile.web
        image: ottertune-web
        container_name: web
        expose:
          - "8000"
        ports:
          - "8000:8000"
        links:
          - backend
          - rabbitmq
        depends_on:
          - backend
          - rabbitmq
        environment:
          DEBUG: 'true'
          ADMIN_PASSWORD: 'changeme'
          BACKEND: 'mysql'
          DB_NAME: 'ottertune'
          DB_USER: 'root'
          DB_PASSWORD: 'ottertune'
          DB_HOST: 'backend'
          DB_PORT: '3306'
          DB_OPTS: '{}'
          MAX_DB_CONN_ATTEMPTS: 30
        working_dir: /app/website
        entrypoint: ./start.sh
        labels:
          NAME: "ottertune-web"
        networks:
          - ottertune-net

    driver:
        build:
          context: ../
          dockerfile: ./docker/Dockerfile.driver
        image: ottertune-driver
        container_name: driver
        depends_on:
          - web
        environment:
          DEBUG: 'true'
        working_dir: /app/driver
        labels:
          NAME: "ottertune-driver"
        networks:
          - ottertune-net

    backend:
        image: mysql:5.7
        container_name: backend
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 'ottertune'
          MYSQL_PASSWORD: 'ottertune'
          MYSQL_DATABASE: 'ottertune'
        expose:
          - "3306"
        ports:
          - "3306:3306"
        labels:
          NAME: "ottertune-backend"
        volumes:
          - mysql_data:/var/lib/mysql
        networks:
          - ottertune-net

    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        restart: always
        hostname: "rabbitmq"
        environment:
           RABBITMQ_DEFAULT_USER: "guest"
           RABBITMQ_DEFAULT_PASS: "guest"
           RABBITMQ_DEFAULT_VHOST: "/"
        expose:
           - "15672"
           - "5672"
        ports:
           - "15673:15672"
           - "5673:5672"
        labels:
           NAME: "rabbitmq"
        networks:
          - ottertune-net
volumes:
   mysql_data:
networks:
   ottertune-net:
      driver: bridge

